# Trying out different classifiers

In [1]:
# Import the necessary libraries
import numpy as np
from sklearn import datasets
# Libraries for the classifiers
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier
from sklearn import svm
# Libraries for the metrics
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Load and parse the data file
iris = datasets.load_iris()
iris_X = iris.data
iris_Y = iris.target
np.unique(iris_Y)

# Split iris data in train and test data
# A random permutation, to split the data randomly
np.random.seed ( 0 )
indices = np.random.permutation(len(iris_X))
# Take some elements from the shuffled array
iris_X_train = iris_X[indices[:-10]]
iris_Y_train = iris_Y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_Y_test = iris_Y[indices[-10:]]

In [2]:
# Keep in mind the desired labels:
iris_Y_test

array([1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

## Test 1 - Naive Bayes classifier

In [3]:
gnb = GaussianNB()
gnb.fit(iris_X_train, iris_Y_train)
gnb.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

### Evaluation 1.1 - Accuracy Score

In [4]:
acc_gnb = accuracy_score(iris_Y_test, gnb.predict(iris_X_test))
acc_gnb

0.90000000000000002

### Evaluation 1.2 - Cross-validation

In [5]:
score_gnb = cross_val_score(gnb, iris_X, iris_Y, cv=5, n_jobs=-1)
print(score_gnb)

[ 0.93333333  0.96666667  0.93333333  0.93333333  1.        ]


## Test 2 - Neural Network

In [6]:
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)

clf.fit(iris_X_train, iris_Y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [7]:
clf.predict(iris_X_test)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Test 2.1 - Accuracy Score

In [8]:
acc_clf = accuracy_score(iris_Y_test, clf.predict(iris_X_test))
acc_clf

0.20000000000000001

### Test 2.2 - Cross-validation

In [9]:
score_clf = cross_val_score(clf, iris_X, iris_Y, cv=5, n_jobs=-1)
print(score_clf)

[ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]


## Test 3 - SVM

In [10]:
mySVC = svm.SVC(kernel='linear', C=1)
mySVC.fit(iris_X_train, iris_Y_train)
mySVC.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])

### Eval 3.1 - Accuracy Score

In [11]:
acc_svc = accuracy_score(iris_Y_test, mySVC.predict(iris_X_test))
acc_svc

0.90000000000000002

### Eval 3.2 - Cross-validation

In [12]:
score_svc = cross_val_score(mySVC, iris_X, iris_Y, cv=5, n_jobs=-1)
print(score_svc)

[ 0.96666667  1.          0.96666667  0.96666667  1.        ]


## Comparing results

In [13]:
print("Accuracy Score results")
print("------------------------")
print("NB Classifier:")
print(acc_gnb)
print("Neural Network Classifier:")
print(acc_clf)
print("SVC Classifier:")
print(acc_svc)
print("")
print("")
print("Cross Validation results")
print("------------------------")
print("NB Classifier:")
print(score_gnb)
print("Neural Network Classifier:")
print(score_clf)
print("SVC Classifier:")
print(score_svc)


Accuracy Score results
------------------------
NB Classifier:
0.9
Neural Network Classifier:
0.2
SVC Classifier:
0.9


Cross Validation results
------------------------
NB Classifier:
[ 0.93333333  0.96666667  0.93333333  0.93333333  1.        ]
Neural Network Classifier:
[ 0.33333333  0.33333333  0.33333333  0.33333333  0.33333333]
SVC Classifier:
[ 0.96666667  1.          0.96666667  0.96666667  1.        ]


Among the tested classifiers, SVC proves to be the best one for our study case.

It is comparable to the K-NN Classifier, k = 8, from the previous exercise, which is the best value for the K-NN in our case, with an accuracy of 1.0 .